services:
  - type: web
    name: letter-app-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: RECEIVER_EMAIL
        sync: false
      - key: VALID_USERNAMES
        sync: false
      - key: USER_DOB
        sync: false 